server:
  port: 8080

spring:
#  r2dbc:
#    url: r2dbc:h2:mem:///crypto-exchange
#    username: sa
#    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:tcp://127.0.0.1:9999/mem:crypto-exchange
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    hikari:
      schema: PUBLIC
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
logging:
  level:
    org:
      springframework:
        security: TRACE